base_url = "https://kstr0.xyz"
title = "kstr0"
description = "Personal blog"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "1337"

[extra]
author = "Kstr0"
github = "kstr0git"
