name = "Swiss-Zen"
description = "Minimalistic blog theme"
license = "MIT"
homepage = "https://github.com/kstr0/swiss-zen"
min_version = "0.12.0"

[extra]

[author]
name = "Kstr0"
homepage = "https://kstr0.xyz"
